[build]
  # Directory to serve files from
  publish = "."
  
  # No build command needed for static site
  command = "echo 'No build process needed for static site'"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for single page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://js.stripe.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self' https://api.stripe.com https://api.whop.com;"

# Form handling
[[forms]]
  name = "contact"
  action = "/contact-success"
  method = "POST"

# Environment variables (set in Netlify dashboard)
# STRIPE_PUBLISHABLE_KEY
# WHOP_API_KEY
# WHOP_COMPANY_ID 